# Generated by Django 5.1.1 on 2024-09-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionpackage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='package_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpackage',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
