# Generated by Django 5.1.1 on 2024-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionpackage_package_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpackage',
            name='package_type',
        ),
        migrations.AlterField(
            model_name='subscriptionpackage',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=200),
        ),
    ]
