# Generated by Django 5.1.1 on 2024-09-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_question_created_at_alter_question_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('student', 'student'), ('draft', 'Draft'), ('submitted_to_admin', 'Submitted to Admin'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('returned_to_creator', 'Returned to Creator'), ('published', 'Published')], default='draft', max_length=50),
        ),
    ]
